plugins:
  - uses:
      - plugin: https://damaged-alysa-moniswap-b2f3cc8b.koyeb.app
        with:
          disabledCommands: []
          miscellaneous:
            maxConcurrentTasks: 3
          configurableResponse: "This is Kingsley's personal Ubiquity OS"
        runsOn:
          ["issue_comment", "issue_comment.created", "issue_comment.edited"]
